version: '2'
services:
  test:
    image: coda_db_test
    build:
      context: .
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Release -DENABLE_MEMCHECK=ON -DCMAKE_CXX_COMPILER=g++
    links:
      - mysql
      - postgres
    working_dir: /usr/src/build
    environment:
      MYSQL_URI: mysql://mysql:3306/test
      POSTGRES_URI: postgres://test:test@postgres:5432/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:3306 -wait tcp://postgres:5432 -timeout 30s make test ARGS=-V
  coverage:
    image: coda_db_coverage
    build:
      context: .
      args:
          CMAKE_DEFINES: -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DCMAKE_CXX_COMPILER=g++
    environment:
      - TRAVIS_JOB_ID
    links:
      - mysql
      - postgres
    working_dir: /usr/src/build
    environment:
      MYSQL_URI: mysql://mysql:3306/test
      POSTGRES_URI: postgres://test:test@postgres:5432/test
    depends_on:
      - mysql
      - postgres
    command: dockerize -wait tcp://mysql:3306 -wait tcp://postgres:5432 -timeout 30s make coda_db_coverage_coveralls TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
  mysql:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  postgres:
    image: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
